#!/usr/bin/env sh
set -eu

name=$(basename "$0")

if [ -n "${FAKE_COMMAND_LOG:-}" ]; then
  printf '%s' "$name" >> "$FAKE_COMMAND_LOG"
  for arg in "$@"; do
    printf '\t%s' "$arg" >> "$FAKE_COMMAND_LOG"
  done
  printf '\n' >> "$FAKE_COMMAND_LOG"
fi

command_dir="${FAKE_COMMAND_BEHAVIOR_DIR:-}/$name"

if [ -d "$command_dir" ]; then
  [ ! -f "$command_dir/stdout" ] || cat "$command_dir/stdout"
  [ ! -f "$command_dir/stderr" ] || cat "$command_dir/stderr" >&2

  if [ -f "$command_dir/create_executables" ]; then
    while IFS= read -r executable; do
      [ -n "$executable" ] || continue
      ln -sf "$(dirname "$0")/_fake_command" "${FAKE_COMMAND_BIN:?}/$executable"
    done < "$command_dir/create_executables"
  fi

  if [ -f "$command_dir/create_executables_when" ]; then
    while IFS="	" read -r expected_args executable; do
      [ -n "$expected_args" ] || continue
      [ "$expected_args" = "$*" ] || continue
      [ -n "$executable" ] || continue
      ln -sf "$(dirname "$0")/_fake_command" "${FAKE_COMMAND_BIN:?}/$executable"
    done < "$command_dir/create_executables_when"
  fi

  if [ -f "$command_dir/status" ]; then
    exit "$(cat "$command_dir/status")"
  fi
fi

exit 0
