" Generated by vim-plug
" Thu 28 Jul 2022 04:15:14 AM UTC
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'e10fcf22dcc0441da3c984e26ae2e467b0ae554f'
silent! let g:plugs['fzf'].commit = 'ecc418ba77e52660ffdd9ed84727b12c3f377680'
silent! let g:plugs['fzf.vim'].commit = 'c311c0a95fc2529c26ab36a8f530e9dd4426304c'
silent! let g:plugs['undotree'].commit = 'bfc9b060c9e84497b15b4d602095ba008383b664'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-endwise'].commit = '210bec5b5306023ba7b04a4e5b0824755ea51d5d'
silent! let g:plugs['vim-eunuch'].commit = '74e0e1662cc9ed3d58ba3e3de20eb30ac4039956'
silent! let g:plugs['vim-fugitive'].commit = '9a13fc87c4ab83ea81e71ccad9b846a5eb31a998'
silent! let g:plugs['vim-plug'].commit = '8fdabfba0b5a1b0616977a32d9e04b4b98a6016a'
silent! let g:plugs['vim-rails'].commit = '6bc0c7826d68f8c44c8347a3012aa79ade4f0a22'
silent! let g:plugs['vim-rhubarb'].commit = '09b9b1ca86d3e55d4ed80770a053beaf9d2edbef'
silent! let g:plugs['vim-sensible'].commit = '226203be173bf0b95ee2a5cb6575ae604b3f9f7a'
silent! let g:plugs['vim-sleuth'].commit = '1d25e8e5dc4062e38cab1a461934ee5e9d59e5a8'

PlugUpdate!

