" Generated by vim-plug
" Thu 24 Feb 2022 06:10:12 AM UTC
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['fzf'].commit = '9cb7a364a31bdb882d873807774bdcf6fad0c9e4'
silent! let g:plugs['fzf.vim'].commit = '1f7bfa4007043c30027b2cd79625e8aac5cff1f9'
silent! let g:plugs['undotree'].commit = '08e259be24d4476c1ee745dc735eefd44f90efdc'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'e2c9e01abd2734919e65dd6fe6c84ca2a9b65a7d'
silent! let g:plugs['vim-fugitive'].commit = 'c29ef11cd6478da675678265e76f9e527843876f'
silent! let g:plugs['vim-plug'].commit = 'e300178a0e2fb04b56de8957281837f13ecf0b27'
silent! let g:plugs['vim-rails'].commit = 'de73f6d1b0bf1b2af2d576f3420fc861af14769f'
silent! let g:plugs['vim-rhubarb'].commit = '977b3ccbad1f7e5370354ae409fb2ea4a7ce2058'
silent! let g:plugs['vim-sensible'].commit = '2d9f34c09f548ed4df213389caa2882bfe56db58'
silent! let g:plugs['vim-sleuth'].commit = '27156fb69450ddef8e1bbec6afa71896681ad38a'

PlugUpdate!
