" Generated by vim-plug
" Tue 04 Jun 2024 07:32:30 AM UTC
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'c7c41e157478fc9d4f65e9f640bfce75fa211fd7'
silent! let g:plugs['copilot.vim'].commit = '53d3091be388ff1edacdb84421ccfa19a446a84d'
silent! let g:plugs['fzf'].commit = '3ee1fc203406debab432dbf3cb67f37ea7cb3d30'
silent! let g:plugs['fzf.vim'].commit = '0a80e43f9027ec64213d602dbb0b22d65a072ca8'
silent! let g:plugs['nightfox.nvim'].commit = 'df75a6a94910ae47854341d6b5a6fd483192c0eb'
silent! let g:plugs['tokyonight.nvim'].commit = '7e5ef71a103e7de5fe6c05f5d6ab97d1640f08cf'
silent! let g:plugs['undotree'].commit = '56c684a805fe948936cda0d1b19505b84ad7e065'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-endwise'].commit = '3719ffddb5e42bf67b55b2183d7a6fb8d3e5a2b8'
silent! let g:plugs['vim-eunuch'].commit = '8fb3904be27b6b60d086f87c2570085902414069'
silent! let g:plugs['vim-fugitive'].commit = '4f59455d2388e113bd510e85b310d15b9228ca0d'
silent! let g:plugs['vim-plug'].commit = 'db37a8a29a61a55808fb7c6e1af63940d5478199'
silent! let g:plugs['vim-rails'].commit = '8972461e64c7c4bf049f2f86ea1bc571e8077b55'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-sensible'].commit = '3e878abfd6ddc6fb5dba48b41f2b72c3a2f8249f'
silent! let g:plugs['vim-sleuth'].commit = '1cc4557420f215d02c4d2645a748a816c220e99b'

PlugUpdate!

